export const URL_PARAMS = {
  PITCH: 'pitch',
  YAW: 'yaw',
  ROLL: 'roll',
  GAP: 'gap',
  FOV: 'fov',
  SPEED: 'speed',
  ANIMATION_PRESET: 'animation-preset',
  EASING_TYPE: 'easing-type',
  EASING_STRENGTH: 'easing-strength',
  OVERSHOOT: 'overshoot',
  BOUNCES: 'bounces',
  STEPS: 'steps',
  STEP_DURATION: 'step-duration',
  AXIS_TYPE: 'axis-type',
  AXIS_X: 'axis-x',
  AXIS_Y: 'axis-y',
  AXIS_Z: 'axis-z',
  DIRECTION: 'direction',
  PAUSE_DURATION: 'pause-duration',
  REPEAT_COUNT: 'repeat-count',
} as const
